# This workflow ensures all code being pushed to your repository is formatted.
# Feel free to change it so it happens on pulls! Look over Github's documentation on actions if you're confused
name: Unity Auto Format
description: Simply supply the path to your scripts directory to the action!
author: Ty Irvine
branding:
  icon: 'align-left'
  color: 'orange'

# This is where we gather the inputs for the action
inputs:
  path:
    description: 'The path to the scripts you want formatted ⤵︎'
    required: true
    default: './Assets/Scripts/'
  
# The inputs above are then fed into a the Dockerfile
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
